### ISSUE TITLE
Cant use addon with non mana users in group

### ISSUE THREAD

**Issue by TrevorStubblefield** [apottere/BRDEscortFarm#1]
addon wont work if someone doesnt have mana (warriors)

**Comment by apottere** [comment]
Thanks for the bug report!

This was definitely an oversight, I'll make sure to update the addon to kick any classes that don't have mana from the party.

**Comment by TrevorStubblefield** [comment]
Actually we wanted to do 4 mages 1 warrior to boost (guildie) could it be usable with a warrior in group?

**Comment by apottere** [comment]
lol yeah I was just joking.  I'll take a look tomorrow and post a fix.

**Comment by TrevorStubblefield** [comment]
Awesome, thanks!

**Comment by mhomolak** [comment]
Any movement on this fix?

**Comment by Ecalzo** [comment]
@mhomolak I have opened a PR that may fix this: https://github.com/apottere/BRDEscortFarm/pull/2

**Comment by apottere** [comment]
Sorry for the delay, this should be fixed with that commit but I don't really have a way to test it for real.  Let me know how it goes!
